import type { NextConfig } from "next"















































































































































































































































































































































































































**Status**: Ready for development use**Last Updated**: 2025-12-15  ---- [Next.js Docker](https://nextjs.org/docs/deployment#docker-image)- [FastAPI Docker](https://fastapi.tiangolo.com/deployment/docker/)- [Docker Compose Docs](https://docs.docker.com/compose/)- [Docker Docs](https://docs.docker.com/)## 📚 Resources---5. **Security**: Scan images with `docker scan`4. **Scaling**: Add load balancer for multiple frontend instances3. **Alerting**: Set up notifications for container failures2. **Monitoring**: Add Prometheus + Grafana1. **CI/CD**: Set up GitHub Actions to auto-build images## 🔗 Next Steps---```docker-compose pull            # Pull latest imagesdocker-compose build --no-cache # Rebuild without cachedocker-compose exec <svc> sh   # Shell into servicedocker-compose logs -f         # Follow logsdocker-compose ps              # List servicesdocker-compose restart         # Restart alldocker-compose down            # Stop and removedocker-compose up -d           # Start in background```bash### Docker Compose Cheat Sheet```docker logs bitcoin-backend -f# View container logsdocker cp bitcoin-backend:/app/logs/app.log ./# Copy files from containerdocker exec -it bitcoin-backend bash# Execute command in containerdocker inspect bitcoin-backend# Inspect containerdocker images# List all imagesdocker ps -a# List all containers```bash### Useful Commands## 🎓 Learning Docker---```NODE_ENV=productionNEXT_PUBLIC_API_URL=http://localhost:8000/api/v1```env### Frontend (.env.local)```SUPABASE_KEY=your_supabase_keySUPABASE_URL=your_supabase_url# External Services (optional)DATA_RAW_PATH=/app/data/rawDATA_HOT_PATH=/app/data/hot# Data PathsLOG_LEVEL=infoPYTHONPATH=/appHOST=0.0.0.0PORT=8000# API Server```env### Backend (.env)## 📝 Environment Variables---```docker rmi bitcoin-frontend:latestdocker rmi bitcoin-backend:latest# Remove specific imagesdocker system prune -a# Remove all unused Docker resourcesdocker-compose down -v# Stop and remove containers, networks, volumes```bash### Clean Up Everything```docker-compose down```bash### Remove Stopped Containers## 🧹 Cleanup---```curl http://localhost:8000/api/v1/healthdocker-compose ps# 3. Verifydocker-compose up -d --build# 2. Rebuild affected servicesgit pull origin main# 1. Pull latest code```bash### Deploy Code Changes```curl -X POST http://localhost:8000/api/v1/refresh-data# Option 3: API endpointdocker-compose restart backend# Option 2: Restart (triggers startup update)docker-compose exec backend python src/services/auto_update_data.py# Option 1: Manual trigger```bash### Daily Data Update## 🔄 Update Workflow---```docker-compose logs -f backend# Follow logs for specific servicedocker-compose logs --since 2023-12-15T10:00:00# Since specific timedocker-compose logs --tail=100# Last 100 linesdocker-compose logs -f# All services```bash### View Logs```curl http://localhost:3000/api/health | jq# Frontend healthcurl http://localhost:8000/api/v1/health | jq# Backend health```bash### Check Health```docker stats bitcoin-backend# Specific containerdocker stats# Real-time resource usage```bash### View Container Stats## 📈 Monitoring---4. **Automated backups** with cron jobs3. **Resource limits** to prevent memory leaks2. **Nginx** reverse proxy for SSL and caching1. **Gunicorn** (multi-worker) instead of Uvicorn### Production Optimizations```docker-compose -f docker-compose.prod.yml up -d# Start in production modedocker-compose -f docker-compose.prod.yml build# Use production docker-compose file```bash### Build Production Images## 🚀 Production Deployment---```docker-compose exec backend python -c "import sys; print(sys.path)"# Check Python pathdocker-compose build --no-cache backend# Rebuild with no cache```bash### "Module not found" Errors```docker-compose exec frontend env | grep API_URL# Check environment variabledocker-compose exec frontend curl http://backend:8000/api/v1/health# Verify backend is healthydocker network inspect bitcoin-platform# Check network```bash### Frontend Can't Reach Backend```docker-compose exec backend python src/services/auto_update_data.py# Manually trigger data updatedocker-compose exec backend ls -lh data/hot/# Check data filesdocker-compose exec backend curl http://localhost:8000/api/v1/health# Check if backend is responding```bash### Backend Health Check Fails```docker system prune -a  # Clean up# 3. Out of disk spacesudo chown -R $USER:$USER data/ logs/# 2. Permission deniedpkill -f uvicorn    # Kill old processsudo lsof -i :8000  # Check what's using port 8000# 1. Port already in use# Common issues:docker-compose logs backend# Check logs```bash### Container Won't Start## 🐛 Troubleshooting---```# Backend will fetch fresh data on startupdocker-compose up -drm -rf data/hot/*.parquetdocker-compose down# Remove all data (CAREFUL!)```bash### Reset Data```tar -xzf bitcoin-data-20251215.tar.gz# Restoretar -czf bitcoin-data-$(date +%Y%m%d).tar.gz data/# Backup data directory```bash### Backup Data- Changes persist across container restarts- Logs directory: `./logs` → mounted as volume- Data directory: `./data` → mounted as volume### Current Setup (Development)## 📊 Data Management---```docker-compose up -d backenddocker-compose build backend# Or rebuild specific servicedocker-compose up -d --build# If you modify requirements.txt or package.json```bash### Rebuild After Dependency Changes```docker-compose restart backend# Or restart backend (triggers startup auto-update)docker-compose exec backend python src/services/auto_update_data.py# Run auto-update script```bash### Update Data Inside Container- **Frontend**: Changes to `frontend-nextjs/` auto-reload- **Backend**: Changes to `src/` directory auto-reloadThe `docker-compose.override.yml` file automatically enables hot reload:### Hot Reload (Auto-enabled in dev)## 🔧 Development Workflow---```docker-compose exec backend python src/services/auto_update_data.pydocker-compose exec backend bash# Execute command in running containerdocker-compose logs -f frontenddocker-compose logs -f backend# View logs for specific servicedocker-compose restart backend# Restart a specific servicedocker-compose down -v# Stop and remove volumes (CAREFUL: deletes data!)docker-compose down# Stop and remove containersdocker-compose stop# Stop services```bash### 3. Common Commands```http://localhost:3000# Test frontend (open in browser)curl http://localhost:8000/api/v1/health# Test backenddocker-compose ps# Check status```bash### 2. Verify Services```docker-compose logs -f# View logsdocker-compose up -d# Start all services in detached modedocker-compose build# Build images (first time only, ~5-10 minutes)cd /home/azune/Documents/coding/Data-analysis-bitcoin```bash### 1. Build and Start Services## 🎯 Quick Start (Development)---```newgrp docker  # Refresh group membershipsudo usermod -aG docker $USER  # Add yourself to docker groupsudo apt install docker.io docker-composesudo apt update# If not installed on Linux:docker-compose --version  # Should be >= 1.29docker --version  # Should be >= 20.10# Check Docker installation```bash### 🚀 Prerequisitesconst nextConfig: NextConfig = {
  eslint: {
    ignoreDuringBuilds: true,
  },
  typescript: {
    ignoreBuildErrors: true,
  },
  images: {
    unoptimized: true,
  },
  // Enable standalone output for Docker
  output: 'standalone',
}

export default nextConfig
